version: '3.7'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: products-platform
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: